language: node_js
node_js:
 - "6.12.3"
 - "8.9.4"
 - "9.5.0"
script:
 - npm test
 - npm run-script lint
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MEhhbGYtU2hvdCUzQWhhbGYtc2hvdC51ay8lMjFxUE5PblVzTnNaclRvRlpxeEIlM0FoYWxmLXNob3QudWs"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
